/*
 * foodFixes.js — per-name accuracy overlay for the food catalog.
 *
 * Why this exists:
 *  - Many foods in foodSeedData.js shipped WITHOUT a description (the seed
 *    left ~286 distinct names / 351 rows undescribed).
 *  - A batch of nuts + dried fruits + figs + dates all shared one identical
 *    nutrition template (179 kcal, 5p/15c/11f, 35g) — impossible, an almond
 *    is not equal to a raisin.
 *  - Coconut was listed at 121 kcal per 150 g serving (~354 kcal per 100 g is
 *    the real fresh-coconut-flesh value).
 *
 * All overrides are keyed by the food NAME (safe: descriptions are consistent
 * per name across every region/category). Nutrition overrides are PER SERVING
 * (the same convention foodSeedData.js uses), so toPer100g() still applies.
 */

export const DESCRIPTIONS = {
  /* ── vegetable ─────────────────────────────────────────────── */
  "Okra / Ladyfinger": "Tender green pods, mild and slightly sweet",
  "Okra": "Tender green pods, mild and slightly sweet",
  "Bottle Gourd": "Mild, watery squash, very low in calories",
  "Bitter Gourd": "Deeply bitter pale-green gourd, prized for health",
  "Fenugreek Leaves": "Earthy, slightly bitter leafy greens",
  "Fenugreek": "Earthy, slightly bitter leafy greens",
  "Spinach": "Tender leafy greens, rich in iron",
  "Collard Greens": "Hearty dark leafy greens",
  "Radish": "Crisp, pungent white or red root",
  "Turnip": "Mild, sweet white root vegetable",
  "Turnips": "Mild, sweet white root vegetable",
  "Cauliflower": "Mild white florets in a leafy head",
  "Cabbage": "Crunchy green (or red) leafy head",
  "Carrots": "Sweet orange root, rich in vitamin A",
  "Carrot": "Sweet orange root, rich in vitamin A",
  "Peas": "Sweet round green legumes in pods",
  "Potato": "Starchy, versatile white-fleshed tuber",
  "Potatoes": "Starchy, versatile white-fleshed tuber",
  "Onion": "Pungent allium bulb, base of most curries",
  "Onions": "Pungent allium bulb, base of most curries",
  "Tomato": "Sweet-tart juicy red fruit, curry base staple",
  "Tomatoes": "Sweet-tart juicy red fruit, curry base staple",
  "Eggplant / Brinjal": "Soft purple aubergine that soaks up masala",
  "Eggplant": "Soft purple aubergine that soaks up masala",
  "Ridge Gourd": "Mild ridged gourd, soft and light when cooked",
  "Tinda (Indian Squash)": "Small round green squash, mild and juicy",
  "Drumsticks": "Long green pods of the moringa tree",
  "Cluster Beans": "Flat green beans with a slight bitterness",
  "Colocasia": "Starchy taro root, nutty and creamy",
  "Arvi (Colocasia)": "Starchy taro root, nutty and creamy",
  "Sweet Potato": "Naturally sweet, orange-fleshed root",
  "Yam": "Starchy, dense cooking tuber",
  "Garlic": "Pungent allium bulb used to flavor curries",
  "Ginger": "Spicy fresh rhizome, aromatic and warming",
  "Green Chili": "Fiery fresh chili, added for heat",
  "Coriander Leaves": "Fresh, lemony herb, scattered as garnish",
  "Coriander": "Fresh, lemony herb, scattered as garnish",
  "Mint": "Cooling fresh herb used in raita and chutney",
  "Lemon": "Tart citrus fruit, squeezed for tang",
  "Green Mango (raw)": "Tart, firm unripe mango used in achar",
  "Sponge Gourd": "Soft pale gourd, light and watery when cooked",
  "Yardlong Beans": "Extra-long slender green beans",
  "Snake Gourd": "Long, twisting pale gourd with mild flesh",
  "Ivy Gourd": "Small green gourd, tender and mildly sweet",
  "Dedhri (Wild Okra)": "Slimmer, firmer wild variety of okra",
  "Raw Banana": "Starchy unripe banana, cooked like a vegetable",
  "Pumpkin": "Sweet, firm orange squash flesh",
  "Curry Leaves": "Aromatic leaves used in tempering (baghaar)",
  "Fiddlehead Ferns": "Coiled young fern shoots, seasonal delicacy",

  /* ── rice ──────────────────────────────────────────────────── */
  "Biryani": "Aromatic layered rice with spiced meat or vegetables",
  "Biryani (Chicken/Mutton/Beef/Veg)": "Aromatic layered rice with spiced curry",
  "Pulao / Pilaf": "Rice simmered in seasoned stock with meat or vegetables",
  "Chicken Pulao": "Rice cooked with tender chicken and whole spices",
  "Mutton Pulao": "Rice with slow-cooked mutton and whole spices",
  "Beef Pulao": "Rice with beef and aromatic whole spices",
  "Aloo Pulao": "Rice with spiced potatoes, simple and filling",
  "Matar Pulao": "Rice with green peas and gentle spices",
  "Chana Pulao": "Rice with chickpeas, hearty and spiced",
  "Zeera Rice": "Basmati rice tempered with sizzled cumin seeds",
  "Plain Steamed Rice": "Fluffy steamed basmati rice, mild and neutral",
  "Murgh Chawal": "Chicken curry served over steamed rice",
  "Kadhi Chawal": "Tangy yogurt-curry served with rice",
  "Saag Chawal": "Cooked greens served on a bed of rice",
  "Khichdi": "Comforting one-pot rice and lentil porridge",
  "Zarda": "Sweet saffron-tinted rice with nuts and cardamom",
  "Sweet Rice": "Rice sweetened with sugar, ghee and cardamom",
  "Tahari": "One-pot rice cooked with meat or vegetables",

  /* ── curry-kebab ───────────────────────────────────────────── */
  "Chicken Karahi": "Tomato-based chicken curry finished in a karahi wok",
  "Chicken Korma": "Creamy, mildly spiced chicken curry",
  "Chicken Handi": "Chicken curry simmered gently in a clay handi",
  "Chicken Tikka": "Char-grilled marinated chicken pieces",
  "Chicken Jalfrezi": "Stir-fried chicken with peppers in a tangy sauce",
  "Chicken Changezi": "Rich tomato-chili chicken curry, Mughlai style",
  "Chicken Haleem": "Slow-cooked chicken with wheat and lentils",
  "Butter Chicken": "Tandoori chicken folded into a creamy tomato gravy",
  "Mutton Karahi": "Tomato-based mutton curry finished in a karahi wok",
  "Mutton Korma": "Creamy, mildly spiced mutton curry",
  "Mutton Nihari": "Slow-cooked mutton stew in a rich, spiced gravy",
  "Beef Nihari": "Slow-cooked beef stew in a rich, spiced gravy",
  "Mutton Paye": "Mutton trotters in a rich, gelatinous gravy",
  "Beef Paye": "Beef trotters in a rich, gelatinous gravy",
  "Mutton Haleem": "Slow-cooked mutton with cracked wheat and lentils",
  "Kaleji Masala": "Spiced stir-fried liver curry",
  "Korma": "Rich, creamy, mildly spiced curry",
  "Seekh Kebab": "Minced meat molded on skewers and grilled",
  "Shami Kebab": "Flat minced-meat patties bound with yellow lentils",
  "Chapli Kebab": "Spiced flat minced patty, pan-fried crisp",
  "Reshmi Kebab": "Cream-marinated, silky-soft kebab",
  "Gola Kebab": "Tender, softly grilled minced-meat kebab",
  "Malai Boti": "Cream-and-cardamom marinated meat chunks",
  "Tikka Boti": "Marinated meat cubes, char-grilled over coals",
  "Bihari Kebab": "Thin beef steaklet coated in a mild spiced gravy",
  "Galouti Kebab": "Melt-in-the-mouth minced-meat kebab",
  "Bun Kebab": "Spiced patty tucked into a soft toasted bun",

  /* ── dessert ───────────────────────────────────────────────── */
  "Kheer": "Creamy rice pudding with milk, sugar and cardamom",
  "Firni / Phirni": "Silky-ground rice pudding, set and chilled",
  "Gulab Jamun": "Deep-fried milk-solid balls in rose-scented syrup",
  "Ras Malai": "Soft cheese patties in sweetened saffron milk",
  "Rasgulla": "Spongy chenna balls simmered in light syrup",
  "Barfi": "Dense milk-fudge sweet, cut into diamond shapes",
  "Kalakand": "Crumbly sweet made from reduced milk and paneer",
  "Kulfi": "Dense, slow-frozen milk dessert with cardamom",
  "Falooda": "Chilled milk drink with vermicelli, basil seeds and ice cream",
  "Shahi Tukray": "Fried bread slices soaked in sweetened saffron milk",
  "Double Ka Meetha": "Fried bread pudding layered with rabri and nuts",
  "Gajar Halwa": "Slow-cooked grated carrots in ghee, milk and sugar",
  "Suji Halwa": "Golden semolina roasted in ghee with sugar and nuts",
  "Moong Dal Halwa": "Rich halwa made from slow-cooked moong dal and ghee",
  "Atta Halwa": "Wheat-flour halwa roasted in ghee",
  "Besan Halwa": "Gram-flour halwa roasted in ghee, aromatic and dense",
  "Gur Halwa": "Halwa sweetened with jaggery (gur)",
  "Sohan Halwa": "Dense ghee-based halwa studded with nuts, a Multan classic",
  "Meethe Chawal": "Sweetened rice with ghee, cardamom and dry fruit",
  "Sheer Khurma": "Vermicelli cooked in sweetened milk with dates and nuts",
  "Seviyan": "Roasted vermicelli cooked in sweetened milk",
  "Khurma": "Toasted vermicelli pudding, a festive Eid sweet",
  "Jalebi": "Crisp, coiled batter soaked in saffron syrup",
  "Imarti": "Intricately fried lentil spirals in sugar syrup",
  "Balushahi": "Flaky, glazed deep-fried sweet, crisp outside, soft within",
  "Malpua": "Pan-fried sweet pancakes soaked in syrup",
  "Gulgule": "Small sweet wheat fritters, mildly spiced",
  "Motichoor Laddu": "Tiny fried gram-flour pearls bound in syrup",
  "Besan Laddu": "Round gram-flour and ghee sweetmeat",
  "Boondi Laddu": "Fried chickpea-flour droplets bound in sugar syrup",
  "Coconut Laddu": "Grated coconut rolled into sweet balls",

  /* ── drink ─────────────────────────────────────────────────── */
  "Chai": "Milky sweet tea, Pakistan's everyday brew",
  "Doodh Patti": "Strong tea brewed entirely in milk",
  "Kahwa": "Kashmiri green tea with saffron and slivered almonds",
  "Sheer Chai": "Pink Kashmiri tea made with milk and salt",
  "Noon Chai": "Salty pink Kashmiri tea with baking soda",
  "Green Tea": "Light unoxidized tea, brewed plain",
  "Black Tea": "Fully oxidized tea, brewed without milk",
  "Lemon Tea": "Black tea freshened with lemon",
  "Masala Chai": "Milky tea simmered with cardamom, ginger and spices",
  "Adrak Chai": "Milky tea infused with fresh ginger",
  "Elaichi Chai": "Milky tea scented with crushed cardamom pods",
  "Lassi (Plain)": "Thick yogurt drink, sweet or salted",
  "Sweet Lassi": "Thick sweetened yogurt drink",
  "Salted Lassi": "Savory yogurt drink seasoned with salt and cumin",
  "Mango Lassi": "Chilled yogurt blended with ripe mango",
  "Rose Lassi": "Yogurt drink perfumed with rose syrup",
  "Rooh Afza": "Sweet, cooling rose-flavored syrup concentrate",
  "Jam-e-Shirin": "Syrupy sweet sharbat concentrate served chilled",
  "Rooh Afza Milk": "Milk blended with sweet rose syrup",
  "Rooh Afza Lassi": "Yogurt drink swirled with rose syrup",
  "Sugarcane Juice": "Freshly pressed sweet cane juice over ice",
  "Mango Juice": "Blended ripe mango, thick and sweet",
  "Orange Juice": "Freshly squeezed citrus juice",
  "Pomegranate Juice": "Tart-sweet juice of fresh anar seeds",
  "Watermelon Juice": "Light, hydrating blended watermelon",
  "Grape Juice": "Sweet juice pressed from fresh grapes",
  "Apple Juice": "Crisp-sweet juice pressed from apples",
  "Guava Juice": "Fragrant-pink blended guava juice",
  "Lemon Soda": "Fizzy lime drink, sweet-sour and chilled",
  "Imli Sharbat": "Tangy-sweet tamarind cooler",
  "Gur Sharbat": "Jaggery-sweetened refreshing drink",
  "Jamun Sharbat": "Purple cooler made from fresh jamun berries",
  "Aloo Bukhara Sharbat": "Sweet-tart drink made from dried plums",
  "Kanji": "Fermented carrot or beetroot drink, salty and tangy",
  "Kala Khatta": "Sweet-sour purple cooler of black plum syrup",
  "Mango Shake": "Thick milkshake blended with ripe mango",
  "Banana Shake": "Creamy milkshake blended with banana",
  "Strawberry Shake": "Pink milkshake blended with strawberries",
  "Papaya Shake": "Smooth milkshake blended with papaya",
  "Mixed Shake": "Milkshake blended with a mix of fresh fruits",
  "Kulfi Falooda": "Kulfi served with vermicelli, basil seeds and syrup",
  "Rabri Doodh": "Reduced-thickened milk served chilled",
  "Kesar Doodh": "Warm milk steeped with saffron and nuts",
  "Badam Doodh": "Almond-rich milk, sweet and nourishing",
  "Haldi Doodh": "Warm turmeric milk, a traditional remedy",
  "Doodh Soda": "Fizzy milk drink over ice, sweet and creamy",
  "Thandai": "Chilled milk spiced with saffron, fennel and pepper",

  /* ── bread ─────────────────────────────────────────────────── */
  "Bread": "Leavened or flat bread, the everyday staple",
  "Naan": "Soft, leavened tandoor flatbread",
  "Garlic Naan": "Tandoor flatbread brushed with garlic butter",
  "Butter Naan": "Tandoor flatbread finished with butter",
  "Keema Naan": "Tandoor flatbread stuffed with spiced minced meat",
  "Aloo Naan": "Flatbread stuffed with spiced mashed potato",
  "Paneer Naan": "Flatbread stuffed with spiced cottage cheese",
  "Cheese Naan": "Flatbread stuffed with melted cheese",
  "Peshwari Naan": "Tandoor flatbread stuffed with nuts and raisins",
  "Roghni Naan": "Soft, glossy naan enriched with yogurt and ghee",
  "Kulcha": "Soft leavened flatbread, usually tandoor-baked",
  "Paratha": "Flaky, pan-fried layered wheat flatbread",
  "Plain Paratha": "Flaky wheat flatbread pan-fried with oil or ghee",
  "Aloo Paratha": "Paratha stuffed with spiced mashed potato",
  "Gobi Paratha": "Paratha stuffed with spiced cauliflower",
  "Mooli Paratha": "Paratha stuffed with spiced grated radish",
  "Paneer Paratha": "Paratha stuffed with spiced cottage cheese",
  "Keema Paratha": "Paratha stuffed with spiced minced meat",
  "Methi Paratha": "Paratha kneaded with fresh fenugreek leaves",
  "Lachha Paratha": "Highly layered, crisp pan-fried flatbread",
  "Mughlai Paratha": "Rich, multilayer flatbread stuffed and fried",
  "Roti": "Whole-wheat flatbread cooked on a tawa",
  "Chapati": "Whole-wheat flatbread cooked on a tawa",
  "Phulka": "Soft whole-wheat roti that puffs up on flame",
  "Tandoori Roti": "Whole-wheat flatbread baked in a tandoor",
  "Khamiri Roti": "Soft, leavened sourdough flatbread",
  "Missi Roti": "Whole-wheat and gram-flour flatbread",
  "Makki ki Roti": "Cornmeal flatbread, a Punjabi staple",
  "Bajra ki Roti": "Pearl-millet flatbread, hearty and rustic",
  "Dosti Roti": "Two small un-leavened wheat flatbreads",
  "Bhatura": "Deep-fried, puffed leavened bread",
  "Puri": "Small, deep-fried puffed wheat bread",
  "Kachori": "Flaky deep-fried stuffed pastry",
  "Pyaaz Kachori": "Flaky fry stuffed with spiced onion",
  "Dal Kachori": "Flaky fry stuffed with spiced lentil paste",
  "Khasta Kachori": "Extra crisp, flaky stuffed fry",
  "Bedmi Puri": "Deep-fried puri made with urad dal flour",
  "Sheermal": "Saffron-milk flatbread, lightly sweet and tender",
  "Bakarkhani": "Sweet, crisp Mughal-era flatbread",
  "Taftan": "Glazed, leavened saffron flatbread baked in a tandoor",
  "Sattu Roti": "Flatbread made with roasted gram-flour (sattu)",
  "Dhebra": "Gujarati millet flatbread with greens",
  "Koki": "Griddle-fried layered wheat flatbread from Sindh",

  /* ── snack ─────────────────────────────────────────────────── */
  "Snack": "Street-style snack, fried or savory",
  "Samosa": "Crisp triangular pastry with a spiced filling",
  "Aloo Samosa": "Crisp pastry filled with spiced potato",
  "Chicken Samosa": "Crisp pastry filled with spiced chicken",
  "Keema Samosa": "Crisp pastry filled with spiced minced meat",
  "Paneer Samosa": "Crisp pastry filled with spiced cottage cheese",
  "Pakora": "Gram-flour battered fritters, fried crisp",
  "Aloo Pakora": "Potato slices in gram-flour batter, fried crisp",
  "Pyaz Pakora": "Onion ring fritters in gram-flour batter",
  "Palak Pakora": "Spinach-leaf fritters in gram-flour batter",
  "Mirch Pakora": "Green chili fritters in gram-flour batter",
  "Bread Pakora": "Bread slices dipped in batter and fried",
  "Chicken Pakora": "Chicken pieces in crisp gram-flour batter",
  "Paneer Pakora": "Cottage-cheese pieces in crisp batter",
  "Chana Chaat": "Spiced chickpeas tossed with tangy chutney",
  "Aloo Chaat": "Fried potato cubes tossed with chutney and spices",
  "Dahi Bhalla": "Soft fried lentil dumplings in spiced yogurt",
  "Samosa Chaat": "Crushed samosa topped with yogurt and chutneys",
  "Papri Chaat": "Crisp dough wafers with yogurt and chutneys",
  "Gol Gappe": "Crisp shells filled with spiced potato and tangy water",
  "Pani Puri": "Crisp puris filled with spiced potato and flavored water",
  "Bhel Puri": "Puffed rice tossed with chutney, onions and peanuts",
  "Sev Puri": "Crisp puris topped with chutneys, potato and sev",
  "Dahi Puri": "Crisp puris topped with chilled yogurt and chutneys",
  "Ragda Pattice": "Spiced potato patties served with pea curry",
  "Seekh Paratha Roll": "Seekh kebab wrapped in a flaky paratha",
  "Chapli Roll": "Chapli kebab wrapped in a warm paratha",
  "Seekh Roll": "Seekh kebab wrapped flatbread roll",
  "Malai Boti Roll": "Creamy chicken boti wrapped in paratha",
  "Tikka Roll": "Chicken tikka wrapped in a paratha with sauces",
  "Shami Roll": "Shami kebab wrapped in a flatbread roll",
  "Aloo Tikki": "Pan-fried spiced potato patties",
  "Masala Corn": "Roasted corn tossed with lemon and spices",
  "Sweet Corn": "Steamed sweet corn served plain or buttery",

  /* ── fruit ─────────────────────────────────────────────────── */
  "Mango": "Juicy golden tropical fruit, Pakistan's king of fruits",
  "Watermelon": "Large, watery-sweet summer melon",
  "Muskmelon": "Sweet orange-fleshed melon with netted rind",
  "Papaya": "Soft orange tropical fruit with black seeds",
  "Guava": "Fragrant green-skinned fruit, pink or white within",
  "Lychee": "Sweet translucent fruit with a rough red shell",
  "Jamun": "Dark purple berry with a wine-like tang",
  "Falsa": "Small tart purple berries, eaten fresh or as sharbat",
  "Mulberry": "Small sweet-tart berries, purple or white",
  "Cherry": "Glossy sweet red stone fruit",
  "Orange": "Juicy, bright citrus fruit",
  "Kinnow": "Juicy Pakistani mandarin, sweet and easy to peel",
  "Mandarin": "Small, loose-skinned, sweet citrus fruit",
  "Grapefruit": "Large citrus with tart, mildly bitter segments",
  "Sweet Lime": "Pale green citrus with honey-sweet flesh",
  "Apple": "Crisp orchard fruit, sweet or tart",
  "Pear": "Juicy, gritty-textured sweet orchard fruit",
  "Pomegranate": "Tart-sweet fruit packed with jewel-like seeds",
  "Grapes": "Small juicy berries in sweet bunches",
  "Dates": "Naturally sweet dried fruit of the date palm",
  "Figs": "Soft, sweet fruit eaten fresh",
  "Banana": "Creamy, sweet potassium-rich fruit",
  "Coconut": "Firm white flesh of the coconut, rich and faintly sweet",
  "Sapodilla": "Sweet, malty-tasting brown-skinned fruit",
  "Tamarind": "Sour-sweet tangy pod, used in chutneys and curries",
  "Amla": "Small green Indian gooseberry, tart and rich in vitamin C",
  "Wood Apple": "Hard-shelled fruit with sticky, sweet-sour pulp",
  "Jujube": "Small date-like fruit, crisp when fresh and chewy when dried",
  "Almond": "Firm, buttery-textured nut in a hard shell",
  "Walnut": "Mild, buttery nut in a ridged shell",
  "Cashew": "Creamy, curved nut, sweet and mild",
  "Raisin": "Sun-dried grape, intensely sweet",
  "Pistachio": "Green nut that splits open naturally",
  "Pine Nut": "Small, soft ivory nut with a sweet resinous taste",
  "Dried Apricot": "Intensely sweet preserved apricot with a chewy bite",
  "Dried Plum": "Chewy, sweet-tart dried plum (prune)",
  "Dried Fig": "Chewy, honey-sweet fig dried whole",

  /* ── wrong-description fixes ───────────────────────────────── */
  "Cherry Tomato": "Small, sweet bite-sized tomatoes",
  "Turnip Greens": "Leafy greens of the turnip, mildly peppery",
};

/*
 * Per-serving nutrition corrections. Values mirror foodSeedData.js
 * convention (per 1 typical serving, servingG grams).
 */
export const NUTRITION_FIXES = {
  /* Dates & dried fruits */
  "Dates": { kcal: 99, proteinG: 0.9, carbsG: 26.1, fatG: 0.1 },
  "Dates (Khajoor)": { kcal: 99, proteinG: 0.9, carbsG: 26.1, fatG: 0.1 },
  "Gwadar Date": { kcal: 99, proteinG: 0.9, carbsG: 26.1, fatG: 0.1 },
  "Figs": { kcal: 26, proteinG: 0.8, carbsG: 6.6, fatG: 0.2 },
  "Figs (Anjeer)": { kcal: 26, proteinG: 0.8, carbsG: 6.6, fatG: 0.2 },
  "Dried Fig": { kcal: 87, proteinG: 1.2, carbsG: 22.5, fatG: 0.3 },
  "Dried Apricot": { kcal: 84, proteinG: 1.4, carbsG: 21.9, fatG: 0.3 },
  "Dried Plum": { kcal: 84, proteinG: 0.9, carbsG: 22.2, fatG: 0.2 },
  "Raisin": { kcal: 105, proteinG: 1.1, carbsG: 27.7, fatG: 0.2 },
  /* Fresh regional apricots (35 g serving) */
  "Swat Apricot": { kcal: 17, proteinG: 0.5, carbsG: 3.9, fatG: 0.1 },
  "Quetta Apricot": { kcal: 17, proteinG: 0.5, carbsG: 3.9, fatG: 0.1 },
  "GB Apricot": { kcal: 17, proteinG: 0.5, carbsG: 3.9, fatG: 0.1 },
  "Apricot (Khubani)": { kcal: 72, proteinG: 2.1, carbsG: 17.0, fatG: 0.6 },
  /* Nuts */
  "Almond": { kcal: 203, proteinG: 7.5, carbsG: 7.0, fatG: 17.5 },
  "Almond (Baadaam)": { kcal: 203, proteinG: 7.5, carbsG: 7.0, fatG: 17.5 },
  "Swat Almond": { kcal: 203, proteinG: 7.5, carbsG: 7.0, fatG: 17.5 },
  "Quetta Almond": { kcal: 203, proteinG: 7.5, carbsG: 7.0, fatG: 17.5 },
  "GB Almond": { kcal: 203, proteinG: 7.5, carbsG: 7.0, fatG: 17.5 },
  "Walnut": { kcal: 229, proteinG: 5.4, carbsG: 4.8, fatG: 22.8 },
  "Walnut (Akhrot)": { kcal: 229, proteinG: 5.4, carbsG: 4.8, fatG: 22.8 },
  "Swat Walnut": { kcal: 229, proteinG: 5.4, carbsG: 4.8, fatG: 22.8 },
  "Quetta Walnut": { kcal: 229, proteinG: 5.4, carbsG: 4.8, fatG: 22.8 },
  "GB Walnut": { kcal: 229, proteinG: 5.4, carbsG: 4.8, fatG: 22.8 },
  "Cashew": { kcal: 194, proteinG: 6.3, carbsG: 10.6, fatG: 15.6 },
  "Pistachio": { kcal: 196, proteinG: 7.1, carbsG: 9.5, fatG: 15.9 },
  "Pine Nut": { kcal: 236, proteinG: 4.9, carbsG: 4.6, fatG: 24.3 },
  /* Coconut — fresh flesh is ~354 kcal per 100 g */
  "Coconut": { kcal: 531, proteinG: 5.0, carbsG: 23.0, fatG: 50.0 },
  "Coconut (Nariyal)": { kcal: 531, proteinG: 5.0, carbsG: 23.0, fatG: 50.0 },
};

/**
 * Apply the overlay to a raw foodSeedData record.
 * Returns a new object (seed records are never mutated).
 */
export function applyFixes(food) {
  const description = DESCRIPTIONS[food.name];
  const nutrition = NUTRITION_FIXES[food.name];
  return {
    ...food,
    ...(description != null ? { description } : {}),
    ...(nutrition != null ? nutrition : {}),
  };
}