/*
 * trackerFoodAdditions.js — foods missing from the catalog that the
 * tracker configs reference but no accurate backend row exists for.
 *
 * Each food is the single canonical row for its tracker entry (no
 * duplication by name). Nutrition is per 100g, as prepared; oil_g/oil_kcal
 * describe the added cooking oil per serving. Applied by migration 011.
 */

export const TRACKER_FOOD_ADDITIONS = [
  {
    name: "Daal Mash",
    category: "daal",
    slug: "daal-mash",
    description: "Creamy black gram (urad dal) slow-simmered with aromatic spices",
    baseCalories: 108,
    baseProtein: 7.2,
    baseCarbs: 17.9,
    baseFat: 2.1,
    servingG: 250,
    servingLabel: "1 plate (250g)",
    oilG: 8,
    oilKcal: 72,
  },
  {
    name: "Palak Paneer",
    category: "sabzi",
    slug: "palak-paneer",
    description: "Paneer cubes simmered in spiced puréed spinach",
    baseCalories: 120,
    baseProtein: 5.8,
    baseCarbs: 7.5,
    baseFat: 7.8,
    servingG: 200,
    servingLabel: "1 bowl (200g)",
    oilG: 12,
    oilKcal: 108,
  },
  {
    name: "Beef Qeema",
    category: "curry-kebab",
    slug: "beef-qeema",
    description: "Minced beef cooked with onions, tomatoes and garam masala",
    baseCalories: 190,
    baseProtein: 14.5,
    baseCarbs: 5,
    baseFat: 12.8,
    servingG: 200,
    servingLabel: "1 plate (200g)",
    oilG: 10,
    oilKcal: 90,
  },
  {
    name: "Chicken Kofta",
    category: "curry-kebab",
    slug: "chicken-kofta",
    description: "Juicy minced chicken meatballs in a spiced onion-tomato gravy",
    baseCalories: 165,
    baseProtein: 12,
    baseCarbs: 6,
    baseFat: 9.5,
    servingG: 200,
    servingLabel: "1 plate (200g)",
    oilG: 8,
    oilKcal: 72,
  },
  {
    name: "Jeera Rice",
    category: "rice",
    slug: "jeera-rice",
    description: "Fluffy basmati rice tempered with roasted cumin",
    baseCalories: 165,
    baseProtein: 3.6,
    baseCarbs: 34,
    baseFat: 1.2,
    servingG: 200,
    servingLabel: "1 plate (200g)",
    oilG: 5,
    oilKcal: 45,
  },
  {
    name: "Egg Fried Rice",
    category: "rice",
    slug: "egg-fried-rice",
    description: "Wok-fried rice tossed with eggs, spring onions and soy",
    baseCalories: 168,
    baseProtein: 6.5,
    baseCarbs: 22.5,
    baseFat: 5.6,
    servingG: 250,
    servingLabel: "1 plate (250g)",
    oilG: 6,
    oilKcal: 54,
  },
  {
    name: "Vegetable Pakora",
    category: "snack",
    slug: "vegetable-pakora",
    description: "Crisp gram-flour fritters of onion, potato and spinach",
    baseCalories: 248,
    baseProtein: 4.8,
    baseCarbs: 21.5,
    baseFat: 15.5,
    servingG: 100,
    servingLabel: "1 plate (100g)",
    oilG: 12,
    oilKcal: 108,
  },
  {
    name: "Chicken Roll",
    category: "snack",
    slug: "chicken-roll",
    description: "Paratha-wrapped spiced chicken filling, grilled until crisp",
    baseCalories: 282,
    baseProtein: 11.5,
    baseCarbs: 30,
    baseFat: 12.8,
    servingG: 150,
    servingLabel: "1 roll (150g)",
    oilG: 5,
    oilKcal: 45,
  },
  {
    name: "Vanilla Custard",
    category: "dessert",
    slug: "vanilla-custard",
    description: "Silky milk custard thickened with eggs and vanilla",
    baseCalories: 115,
    baseProtein: 3.1,
    baseCarbs: 20,
    baseFat: 3,
    servingG: 150,
    servingLabel: "1 bowl (150g)",
    oilG: 0,
    oilKcal: 0,
  },
  {
    name: "Desi Omelette",
    category: "breakfast",
    slug: "desi-omelette",
    description: "Fluffy egg omelette with onion, green chili and coriander",
    baseCalories: 176,
    baseProtein: 12,
    baseCarbs: 1.6,
    baseFat: 13.2,
    servingG: 150,
    servingLabel: "1 omelette (150g)",
    oilG: 10,
    oilKcal: 90,
  },
  {
    name: "Aloo Chana",
    category: "curry-kebab",
    slug: "aloo-chana",
    description: "Potatoes and chickpeas in a tangy onion-tomato masala",
    baseCalories: 131,
    baseProtein: 4.9,
    baseCarbs: 20.3,
    baseFat: 3.7,
    servingG: 250,
    servingLabel: "1 plate (250g)",
    oilG: 10,
    oilKcal: 90,
  },
  {
    name: "Besan Ka Chilla",
    category: "breakfast",
    slug: "besan-ka-chilla",
    description: "Savory gram-flour pancake with onion, chilies and herbs",
    baseCalories: 202,
    baseProtein: 8.2,
    baseCarbs: 22.4,
    baseFat: 9,
    servingG: 100,
    servingLabel: "1 chilla (100g)",
    oilG: 7,
    oilKcal: 63,
  },
  {
    name: "Grilled Chicken Breast",
    category: "meat",
    slug: "grilled-chicken-breast",
    description: "Skinless chicken breast grilled with a light spice rub",
    baseCalories: 165,
    baseProtein: 31,
    baseCarbs: 0,
    baseFat: 3.6,
    servingG: 150,
    servingLabel: "1 breast (150g)",
    oilG: 0,
    oilKcal: 0,
  },
  {
    name: "Boiled Eggs",
    category: "meat",
    slug: "boiled-eggs",
    description: "Hard-boiled eggs, a simple high-protein staple",
    baseCalories: 143,
    baseProtein: 12.6,
    baseCarbs: 0,
    baseFat: 9.5,
    servingG: 100,
    servingLabel: "2 boiled eggs (100g)",
    oilG: 0,
    oilKcal: 0,
  },
  {
    name: "Fresh Garden Salad",
    category: "vegetable",
    slug: "fresh-garden-salad",
    description: "Crisp cucumber, tomato, onion and greens with a light dressing",
    baseCalories: 24,
    baseProtein: 1.1,
    baseCarbs: 4.8,
    baseFat: 0.2,
    servingG: 120,
    servingLabel: "1 salad bowl (120g)",
    oilG: 0,
    oilKcal: 0,
  },
  {
    name: "Oatmeal (Milk)",
    category: "breakfast",
    slug: "oatmeal-milk",
    description: "Rolled oats simmered in milk and lightly sweetened",
    baseCalories: 90,
    baseProtein: 3.8,
    baseCarbs: 15,
    baseFat: 2.1,
    servingG: 150,
    servingLabel: "1 bowl (150g)",
    oilG: 0,
    oilKcal: 0,
  },
  {
    name: "Poha (Flattened Rice)",
    category: "breakfast",
    slug: "poha-flattened-rice",
    description: "Flattened rice tossed with peanuts, mustard seeds and turmeric",
    baseCalories: 140,
    baseProtein: 3,
    baseCarbs: 24.8,
    baseFat: 3.2,
    servingG: 200,
    servingLabel: "1 plate (200g)",
    oilG: 5,
    oilKcal: 45,
  },
];