/*
 * trackerFoodFixes.js — accuracy corrections for the tracker-facing foods.
 *
 * Why this exists:
 *  - The two combo foods (Daal Chawal, Halwa Puri) shipped with 0 kcal on
 *    every macro (placeholder rows).
 *  - Several distinct foods shared identical copy-paste templates
 *    (Puri == Aloo Paratha at 374 kcal, Sohan Halwa == Gajar ka Halwa at
 *    391 kcal, Gol Gappe == Dahi Bhalla at 235 kcal, Apple == Orange ==
 *    Guava at 64.7 kcal).
 *  - Many solid foods had a NULL serving_g, so the API silently assumed a
 *    100g serving when presenting per-serving nutrition.
 *
 * All fixes are keyed by the foods.slug (unique, stable). Nutrition is
 * per 100g, as prepared (oil already included in base_*); oil_g/oil_kcal
 * describe the added cooking oil per serving. Applied by migration 010.
 */

export const TRACKER_FOOD_FIXES = {
  "daal-chawal": {
    name: "Daal Chawal",
    baseCalories: 159,
    baseProtein: 7.2,
    baseCarbs: 23.5,
    baseFat: 4.8,
    servingG: 350,
    servingLabel: "1 plate (350g)",
    oilG: 12,
    oilKcal: 108,
  },
  "halwa-puri": {
    name: "Halwa Puri",
    baseCalories: 348,
    baseProtein: 6,
    baseCarbs: 47.5,
    baseFat: 15,
    servingG: 250,
    servingLabel: "1 thali (250g)",
    oilG: 25,
    oilKcal: 225,
  },
  "common-across-pakistan-bread-puri": {
    name: "Puri",
    baseCalories: 478,
    baseProtein: 6.2,
    baseCarbs: 60,
    baseFat: 24.5,
    servingG: 90,
    servingLabel: "1 puri (30g)",
    oilG: 7,
    oilKcal: 63,
  },
  "common-across-pakistan-bread-aloo-paratha": {
    name: "Aloo Paratha",
    baseCalories: 298,
    baseProtein: 7.4,
    baseCarbs: 38.5,
    baseFat: 12.5,
    servingG: 130,
    servingLabel: "1 paratha (130g)",
    oilG: 5,
    oilKcal: 45,
  },
  roti: {
    name: "Roti",
    baseCalories: 297,
    baseProtein: 11,
    baseCarbs: 55,
    baseFat: 4,
    servingG: 70,
    servingLabel: "1 roti (70g)",
    oilG: 0,
    oilKcal: 0,
  },
  "plain-paratha": {
    name: "Plain Paratha",
    baseCalories: 320,
    baseProtein: 8,
    baseCarbs: 42,
    baseFat: 13,
    servingG: 100,
    servingLabel: "1 paratha (100g)",
    oilG: 0,
    oilKcal: 0,
  },
  "punjab-dessert-gajar-ka-halwa": {
    name: "Gajar ka Halwa",
    baseCalories: 230,
    baseProtein: 2.6,
    baseCarbs: 30.5,
    baseFat: 11.9,
    servingG: 150,
    servingLabel: "1 bowl (150g)",
    oilG: 10,
    oilKcal: 90,
  },
  "common-across-pakistan-dessert-sohan-halwa": {
    name: "Sohan Halwa",
    baseCalories: 468,
    baseProtein: 3.2,
    baseCarbs: 55,
    baseFat: 26.8,
    servingG: 100,
    servingLabel: "1 piece (100g)",
    oilG: 15,
    oilKcal: 135,
  },
  "common-across-pakistan-fruit-apple": {
    name: "Apple",
    baseCalories: 52,
    baseProtein: 0.26,
    baseCarbs: 13.81,
    baseFat: 0.17,
    servingG: 150,
    servingLabel: "1 medium apple (150g)",
    oilG: 0,
    oilKcal: 0,
  },
  "common-across-pakistan-fruit-orange": {
    name: "Orange",
    baseCalories: 47,
    baseProtein: 0.94,
    baseCarbs: 11.75,
    baseFat: 0.12,
    servingG: 130,
    servingLabel: "1 medium orange (130g)",
    oilG: 0,
    oilKcal: 0,
  },
  "azad-kashmir-gilgit-baltistan-fruit-guava": {
    name: "Guava (Amrood)",
    baseCalories: 68,
    baseProtein: 2.55,
    baseCarbs: 14.32,
    baseFat: 0.95,
    servingG: 100,
    servingLabel: "1 medium guava (100g)",
    oilG: 0,
    oilKcal: 0,
  },
  mango: {
    name: "Mango",
    baseCalories: 60,
    baseProtein: 0.82,
    baseCarbs: 14.98,
    baseFat: 0.38,
    servingG: 150,
    servingLabel: "1 medium mango (150g)",
    oilG: 0,
    oilKcal: 0,
  },
  "common-across-pakistan-snack-gol-gappe": {
    name: "Gol Gappe",
    baseCalories: 182,
    baseProtein: 4.1,
    baseCarbs: 26.3,
    baseFat: 6.1,
    servingG: 120,
    servingLabel: "1 plate (120g)",
    oilG: 5,
    oilKcal: 45,
  },
  "common-across-pakistan-snack-dahi-bhalla": {
    name: "Dahi Bhalla",
    baseCalories: 208,
    baseProtein: 5.2,
    baseCarbs: 24.6,
    baseFat: 9.7,
    servingG: 120,
    servingLabel: "1 plate (120g)",
    oilG: 7,
    oilKcal: 63,
  },
  "bhindi-masala": {
    name: "Bhindi Masala",
    baseCalories: 100,
    baseProtein: 2.5,
    baseCarbs: 10,
    baseFat: 4.8,
    servingG: 150,
    servingLabel: "1 bowl (150g)",
    oilG: 8,
    oilKcal: 72,
  },
  "aloo-gobi": {
    name: "Aloo Gobi",
    baseCalories: 110,
    baseProtein: 2.5,
    baseCarbs: 15,
    baseFat: 4.3,
    servingG: 150,
    servingLabel: "1 bowl (150g)",
    oilG: 8,
    oilKcal: 72,
  },
  "chicken-biryani": {
    name: "Chicken Biryani",
    baseCalories: 190,
    baseProtein: 9,
    baseCarbs: 24,
    baseFat: 6,
    servingG: 250,
    servingLabel: "1 plate (250g)",
    oilG: 0,
    oilKcal: 0,
  },
  "chicken-pulao": {
    name: "Chicken Pulao",
    baseCalories: 180,
    baseProtein: 8,
    baseCarbs: 25,
    baseFat: 5,
    servingG: 200,
    servingLabel: "1 plate (200g)",
    oilG: 0,
    oilKcal: 0,
  },
  "doodh-patti-chai": {
    name: "Doodh Patti Chai",
    baseCalories: 55,
    baseProtein: 2,
    baseCarbs: 6,
    baseFat: 2,
    servingG: 200,
    servingLabel: "1 cup (200g)",
    oilG: 0,
    oilKcal: 0,
  },
  "sweet-lassi": {
    name: "Sweet Lassi",
    baseCalories: 75,
    baseProtein: 3.5,
    baseCarbs: 10,
    baseFat: 2.5,
    servingG: 250,
    servingLabel: "1 glass (250g)",
    oilG: 0,
    oilKcal: 0,
  },
  "rice-kheer": {
    name: "Rice Kheer",
    baseCalories: 140,
    baseProtein: 3.5,
    baseCarbs: 22,
    baseFat: 4.5,
    servingG: 200,
    servingLabel: "1 bowl (200g)",
    oilG: 0,
    oilKcal: 0,
  },
};